services:
  mysql:
    image: mysql:8.0.12
    container_name: curso_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: curso
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: mcr.microsoft.com/dotnet/sdk:2.1
    container_name: curso_dotnet
    volumes:
      - ./app:/app
    working_dir: /app
    command: tail -f /dev/null
    depends_on:
      - mysql

volumes:
  mysql_data:
